---
title: "STAT 571B Noise Analysis"
author: "Tiffany Le"
output: pdf_document
---

```{r, warning = FALSE}
library(lmerTest)
library(pwr)
noise <- read.csv("noise.csv")
noise$Time.as.Factor <- as.factor(noise$Time.as.Factor)
noise$Day <- as.factor(noise$Day)
noise$Floor <- as.factor(noise$Floor)
noise$Operator <- as.factor(noise$Operator)
```

```{r}
par(mfrow = c(1, 2), mar = c(3, 3, 2, 1), pin = c(3.2, 2.5))
full_noise_aov <- aov(Noise ~ Floor*Day*Time.as.Factor, data = noise)
qq <- qqnorm(coef(full_noise_aov)[-1] * 2, datax = T)
text(qq$x, qq$y + 0.07, labels = names(qq$x), cex = 0.6)
qqnorm(abs(coef(full_noise_aov)[-1] * 2), datax = T)
```

```{r}
noise_aov <- aov(Noise ~ Floor*Day*Time.as.Factor - Floor:Day:Time.as.Factor, data = noise)
anova(noise_aov)
```

```{r, fig.align = "center", out.width = "60%"}
par(mfrow = c(1, 2), mar = c(3, 3, 2, 1), pin = c(3.2, 2.5))
plot(noise_aov, which = 1:2)
```

```{r}
ss_effect <- anova(noise_aov)["Time.as.Factor", "Sum Sq"]
ss_error  <- anova(noise_aov)["Residuals", "Sum Sq"]
df_effect <- anova(noise_aov)["Time.as.Factor", "Df"]
df_error  <- anova(noise_aov)["Time.as.Factor", "Df"]

eta2 <- ss_effect / (ss_effect + ss_error)
f <- sqrt(eta2 / (1 - eta2))


pwr.f2.test(
  u = df_effect,
  v = df_error,
  f2 = f^2,
  sig.level = 0.05
)
```

```{r}
red_noise_aov <- aov(Noise ~ Floor*Time.as.Factor, data = noise, contrasts = list(Floor = contr.sum,
                                                                                  Time.as.Factor = contr.sum))
anova(red_noise_aov)
```

Design unfolded into 4 replicates of 5x2 design.

```{r, fig.align = "center", out.width = "60%"}
par(mfrow = c(1, 2), mar = c(3, 3, 2, 1), pin = c(3.2, 2.5))
plot(red_noise_aov, which = 1:2)
```

All outliers are floor 1.

```{r}
coef(red_noise_aov)
```

```{r}
aggregate(Noise ~ Floor*Time.as.Factor, data = noise, FUN = mean)
```

```{r}
aggregate(Noise ~ Time.as.Factor, data = noise, FUN = mean)
```

Report this in paper as model.

```{r}
block_aov <- lmer(Noise ~ Floor*Time.as.Factor + (1 | Operator), data = noise)
ranova(block_aov)
```

Matrix is singular, random effects require within-group replication.